#!/usr/bin/env python3
"""auto_edition.py — Orquestador de la edición diaria autónoma.

Flujo: preflight → fetch → PUERTA 1 → triage (Ollama, --auto) → polish (Claude)
→ PUERTA 2 (verify_codex) → merge con archivo → PUERTA 3 → publish → informe.
Diseño: docs/superpowers/specs/2026-07-02-auto-edition-design.md

Uso: python3 pipeline/auto_edition.py [--dry-run]
"""
import json
import re
import subprocess
import sys
from datetime import date, datetime, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from distribute import _split_top_level_objects  # parser balanceado ya probado

ROOT = Path(__file__).parent.parent
NEWS_JS = ROOT / "src" / "data" / "news.js"
WORK = ROOT / "pipeline" / "work"
VAULT = Path.home() / "Documents" / "Radar Inmobiliario" / "Contenido"
COLA = VAULT / "Noticias" / "_cola"
PUBLICADO = VAULT / "Noticias" / "Publicado"
RECHAZADAS = VAULT / "Noticias" / "_rechazadas"
ARCHIVO = VAULT / "Noticias" / "_archivo"
EDICIONES = VAULT / "Ediciones"

MIN_SCORE = 5
MAX_ARTICULOS = 4
CAP_ITEMS = 30
FUENTES_BLACKLIST = set()  # nombres de fuente en minúsculas, p.ej. {"forocoches"}


# ── news.js: parse / merge / render ──────────────────────────────────────────

def _balanced_span(text: str, anchor_regex: str, open_ch: str, close_ch: str):
    """Texto del bloque balanceado (incluidos delimitadores) tras el anchor."""
    m = re.search(anchor_regex, text, re.M)
    if not m:
        return None
    i = text.find(open_ch, m.end() - 1)
    if i < 0:
        return None
    depth, in_str, esc = 0, False, False
    for j in range(i, len(text)):
        c = text[j]
        if in_str:
            if esc:
                esc = False
            elif c == "\\":
                esc = True
            elif c == '"':
                in_str = False
            continue
        if c == '"':
            in_str = True
        elif c == open_ch:
            depth += 1
        elif c == close_ch:
            depth -= 1
            if depth == 0:
                return text[i:j + 1]
    return None


def parse_news_data(text: str) -> dict:
    m = re.search(r"^  actualizado:\s*'((?:[^'\\]|\\.)*)'", text, re.M)
    actualizado = re.sub(r"\\(.)", r"\1", m.group(1)) if m else ""
    semana_txt = _balanced_span(text, r"^  semanaResumen:\s*\{", "{", "}") or "{}"
    dest_txt = _balanced_span(text, r"^  destacada:\s*\{", "{", "}") or "{}"
    items_txt = _balanced_span(text, r"^  items:\s*\[", "[", "]") or "[]"
    items = [json.loads(o) for o in _split_top_level_objects(items_txt[1:-1])]
    return {
        "actualizado": actualizado,
        "semanaResumen": json.loads(semana_txt),
        "destacada": json.loads(dest_txt),
        "items": items,
    }


def merge_items(new_items: list, prev_items: list, cap: int = CAP_ITEMS) -> list:
    def key(it):
        return it.get("url") or it.get("slug") or ""
    # I4 — dedup TAMBIÉN dentro de new_items (relanzamientos pueden traer el
    # mismo artículo repetido si el paso previo se ejecutó dos veces).
    merged, seen = [], set()
    for it in new_items:
        k = key(it)
        if k and k in seen:
            continue
        seen.add(k)
        merged.append(it)
    for it in prev_items:
        k = key(it)
        if k and k in seen:
            continue
        seen.add(k)
        merged.append(it)
    return merged[:cap]


def render_news_js(actualizado: str, semana: dict, destacada: dict, items: list) -> str:
    actualizado_js = actualizado.replace("\\", "\\\\").replace("'", "\\'")
    return f"""// Enriched news data for the redesigned "noticias" section.
// Each item carries: fecha, hora, categoria, distrito, fuente, titulo, resumen,
// impactoPrecio (estimated bps for the affected zone), tag (color hint).
// Generated by pipeline/polish_claude.sh + pipeline/auto_edition.py

window.NEWS_DATA = {{
  actualizado: '{actualizado_js}',
  semanaResumen: {json.dumps(semana, indent=2, ensure_ascii=False)},

  // Featured "hero" piece — the lead story
  destacada: {json.dumps(destacada, indent=2, ensure_ascii=False)},

  items: {json.dumps(items, indent=2, ensure_ascii=False)},
}};
"""


def _metricas_reales(survivors: list) -> list:
    """I2 — métricas de la destacada calculadas de los supervivientes reales de
    la puerta 2 (no una reescritura sin verificar del dest_prompt de polish)."""
    distritos = len({s.get("distrito") for s in survivors if s.get("distrito")})
    fuentes = len({s.get("fuente") for s in survivors if s.get("fuente")})
    return [
        {"label": "Noticias hoy", "valor": str(len(survivors)), "delta": f"+{len(survivors)}", "up": True},
        {"label": "Distritos", "valor": str(distritos or 1), "delta": f"+{distritos or 1}", "up": True},
        {"label": "Fuentes", "valor": str(fuentes or 1), "delta": f"+{fuentes or 1}", "up": True},
    ]


def _movimiento_medio(prev: dict) -> str:
    """I2 — movimientoMedio real: media de varAnual de src/data/distritos.js,
    formateada es-ES ('+6,2 %'). Si no hay distritos parseables, conserva el
    valor previo (nunca inventa uno nuevo)."""
    distritos_js = ROOT / "src" / "data" / "distritos.js"
    try:
        text = distritos_js.read_text(encoding="utf-8")
    except OSError:
        text = ""
    valores = [float(v) for v in re.findall(r"varAnual:\s*(-?[\d.]+)", text)]
    if not valores:
        return prev.get("semanaResumen", {}).get("movimientoMedio", "")
    media = sum(valores) / len(valores)
    return f"{media:+.1f} %".replace(".", ",").replace("+", "+")


# ── PUERTA 1: filtro determinista ─────────────────────────────────────────────

_ACCENT_MAP = str.maketrans("áéíóúñ", "aeioun")


def _story_tokens(titulo: str) -> set:
    """I6 — tokens normalizados (sin acentos, min 4 chars) de un titular, para
    detectar la misma historia contada por fuentes distintas."""
    t = (titulo or "").lower().translate(_ACCENT_MAP)
    return {w for w in re.findall(r"[a-z0-9]{4,}", t)}


def filter_candidates(candidates, seen_urls, today, min_score=MIN_SCORE,
                      max_articles=MAX_ARTICULOS, blacklist=FUENTES_BLACKLIST):
    """(aceptados, [(candidato, motivo_descarte), ...]). Candidates ya viene
    ordenado por score desc desde fetch_news.py — el corte max_articles se
    queda con los mejores."""
    fresh = {today.isoformat(), (today - timedelta(days=1)).isoformat()}
    ok, ko = [], []
    for c in candidates:
        tok = _story_tokens(c.get("titulo", ""))
        dup_historia = None
        for a in ok:
            inter = tok & _story_tokens(a.get("titulo", ""))
            denom = max(1, min(len(tok), len(_story_tokens(a.get("titulo", "")))))
            if len(inter) / denom > 0.5:
                dup_historia = a
                break
        if c.get("fecha_iso") not in fresh:
            ko.append((c, f"más de 48h ({c.get('fecha_iso')})"))
        elif c.get("score", 0) < min_score:
            ko.append((c, f"score {c.get('score')} < {min_score}"))
        elif c.get("fuente", "").strip().lower() in blacklist:
            ko.append((c, f"fuente en blacklist: {c.get('fuente')}"))
        elif c.get("url", "") in seen_urls:
            ko.append((c, "duplicado (url ya publicada)"))
        elif dup_historia is not None:
            ko.append((c, "historia duplicada de otra fuente"))
        elif len(ok) >= max_articles:
            ko.append((c, f"cupo diario lleno ({max_articles})"))
        else:
            ok.append(c)
    return ok, ko


def collect_seen_urls(news_items, vault_dirs):
    urls = {it.get("url", "") for it in news_items if it.get("url")}
    for d in vault_dirs:
        if not d.exists():
            continue
        for f in d.glob("*.md"):
            m = re.search(r"^url: '([^']+)'", f.read_text(encoding="utf-8"), re.M)
            if m:
                urls.add(m.group(1))
    return urls


# ── infraestructura del flujo ─────────────────────────────────────────────────

import verify_codex as vc

LOCK = WORK / "last_edition.date"
POLISH_REPROMPT = """Eres el editor de Radar Inmobiliario Madrid. Hoy es {today}.
Reescribe esta noticia. Devuelve SOLO este JSON (sin texto extra ni bloques de código):
{{"titulo":"...(max 100 chars, con datos)","resumen":"...(1-2 frases, max 200 chars)",\
"impacto":"...(max 20 chars)","impactoLabel":"...(max 35 chars)",\
"slug":"...(kebab-case sin acentos, max 70 chars)","fechaISO":"2026-MM-DD",\
"body":[{{"type":"p","dropcap":true,"text":"..."}},{{"type":"p","text":"..."}},\
{{"type":"pullquote","text":"..."}},{{"type":"p","text":"..."}}]}}
El body: 4 bloques, ~250 palabras, sin markdown, solo hechos del material original.
REGLA INNEGOCIABLE: PROHIBIDO añadir cifras, fechas, nombres propios, organismos o
ubicaciones que no estén en el material original. Contexto general sin datos concretos, sí.
Si el material da poco, escribe menos: fidelidad antes que longitud.

Material original:
{art_json}"""


def sh(cmd, **kw):
    """Ejecuta y devuelve CompletedProcess; check=True por defecto."""
    kw.setdefault("check", True)
    kw.setdefault("cwd", ROOT)
    kw.setdefault("capture_output", True)
    kw.setdefault("text", True)
    return subprocess.run(cmd, **kw)


def ollama_alive() -> bool:
    import urllib.request
    try:
        with urllib.request.urlopen("http://localhost:11434/api/tags", timeout=5):
            return True
    except OSError:
        return False


def preflight(report: dict) -> None:
    import shutil as _shutil
    import urllib.request
    # working tree limpio en src/ y en el bundle (C1): si hay cambios sin
    # commitear, intentar descartarlos; si persisten, abortar — inspección manual.
    dirty = sh(["git", "status", "--porcelain", "--", "src",
                "Radar Inmobiliario Madrid.html"]).stdout.strip()
    if dirty:
        sh(["git", "checkout", "--", "src", "Radar Inmobiliario Madrid.html"])
        dirty = sh(["git", "status", "--porcelain", "--", "src",
                    "Radar Inmobiliario Madrid.html"]).stdout.strip()
        if dirty:
            raise SystemExit("ABORT preflight: working tree sucio en src/ — "
                             "inspección manual requerida")
    # red
    try:
        with urllib.request.urlopen("https://www.radarinmobiliario.com/robots.txt", timeout=15):
            pass
    except OSError as e:
        raise SystemExit(f"ABORT preflight: sin red ({e})")
    # ollama (intenta arrancarlo si está caído)
    if not ollama_alive():
        try:
            subprocess.Popen(["ollama", "serve"], stdout=subprocess.DEVNULL,
                             stderr=subprocess.DEVNULL, env=vc._env_with_cli_paths())
            import time
            time.sleep(10)
        except FileNotFoundError:
            pass  # sin binario ollama — seguirá caído, se usará triage_claude
    report["ollama"] = ollama_alive()
    # CLIs
    env_path = vc._env_with_cli_paths()["PATH"]
    report["claude"] = bool(_shutil.which("claude", path=env_path))
    report["codex"] = bool(_shutil.which("codex", path=env_path))
    if not report["claude"] and not report["codex"]:
        raise SystemExit("ABORT preflight: ni claude ni codex disponibles")
    # limpiar cola caducada (>48h) → _archivo/
    ARCHIVO.mkdir(parents=True, exist_ok=True)
    limite = (date.today() - timedelta(days=2)).strftime("%Y%m%d")
    for f in sorted(COLA.glob("*.md")):
        prefix = f.name[:8]
        if prefix.isdigit() and prefix < limite:
            f.rename(ARCHIVO / f.name)
            report.setdefault("archivadas", []).append(f.name)

    # I4 — restos de runs anteriores crasheados: cualquier nota "modo: auto"
    # que siga en la cola es de una ejecución previa que no llegó a publish();
    # archivarla para que el relanzamiento no la reprocese duplicada.
    for f in sorted(COLA.glob("*.md")):
        if "modo: auto" in f.read_text(encoding="utf-8"):
            f.rename(ARCHIVO / f.name)
            report.setdefault("archivadas", []).append(f.name)


def find_note_by_url(url: str, folder: Path):
    for f in folder.glob("*.md"):
        if f"url: '{url}'" in f.read_text(encoding="utf-8"):
            return f
    return None


def reject_note(url: str, motivo: str) -> None:
    """La nota ya está en Publicado/ (polish la movió); trasladar a _rechazadas."""
    RECHAZADAS.mkdir(parents=True, exist_ok=True)
    note = find_note_by_url(url, PUBLICADO)
    if not note:
        return
    text = note.read_text(encoding="utf-8")
    text = text.replace("publicar: publicado", "publicar: rechazado", 1)
    motivo_yaml = motivo[:180].replace("'", "’")
    text = text.replace("---\n", f"---\nrechazo_motivo: '{motivo_yaml}'\n", 1)
    (RECHAZADAS / note.name).write_text(text, encoding="utf-8")
    note.unlink()


def needs_repolish(item: dict) -> bool:
    return len(item.get("body") or []) < 4


def repolish_item(item: dict, source: dict, today_h: str) -> dict:
    """Fallback de pulido vía Codex cuando polish dejó el artículo en modo degradado."""
    prompt = POLISH_REPROMPT.format(today=today_h,
                                    art_json=json.dumps(source, ensure_ascii=False, indent=2))
    try:
        data = vc.extract_json(vc.run_codex(prompt))
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
        data = None
    if data and len(data.get("body") or []) >= 4:
        item.update({k: data[k] for k in
                     ("titulo", "resumen", "impacto", "impactoLabel", "slug", "fechaISO", "body")
                     if k in data})
    return item


def gate3(report: dict) -> None:
    data = parse_news_data(NEWS_JS.read_text(encoding="utf-8"))
    for it in data["items"]:
        if not (it.get("slug") and it.get("titulo") and it.get("fechaISO")):
            raise SystemExit(f"ABORT puerta 3: item incompleto {it.get('slug', '?')}")
    sh([sys.executable, "pipeline/build.py"])
    sh([sys.executable, "pipeline/distribute.py"])
    porcelain = sh(["git", "status", "--porcelain"]).stdout
    allowed = ("src/data/news.js", "Radar Inmobiliario Madrid.html", "dist/",
               "pipeline/work/", "\"Radar Inmobiliario Madrid.html\"")
    for line in porcelain.splitlines():
        if line[:2] == "??":
            continue  # untracked preexistente (CLAUDE.md, scratch…) — no viene del build
        path = line[3:].strip().strip('"')
        if not path.startswith(tuple(a.strip('"') for a in allowed)):
            raise SystemExit(f"ABORT puerta 3: fichero inesperado modificado: {path}")
    report["gate3"] = "OK"


def publish(new_items: list, report: dict) -> None:
    today_h = datetime.now().strftime("%-d %b %Y")
    sh(["git", "add", "src/data/news.js", "Radar Inmobiliario Madrid.html", "dist/",
        "pipeline/work/candidates.json", "pipeline/work/approved.json"])
    sh(["git", "commit", "-m",
        f"noticias: edición auto {today_h}\n\nAutomated by pipeline/auto_edition.py"])
    # I7 — push robusto: rebase antes de empujar y un reintento si el primer
    # push falla (carrera con otro push a main entre el rebase y el push).
    sh(["git", "pull", "--rebase", "origin", "main"])
    try:
        sh(["git", "push", "origin", "main"])
    except subprocess.CalledProcessError:
        sh(["git", "pull", "--rebase", "origin", "main"])
        sh(["git", "push", "origin", "main"])
    report["commit"] = sh(["git", "rev-parse", "--short", "HEAD"]).stdout.strip()
    # esperar deploy: poll al primer artículo nuevo
    import time
    import urllib.request
    url = f"https://www.radarinmobiliario.com/noticia/{new_items[0]['slug']}"
    for _ in range(30):
        try:
            with urllib.request.urlopen(url, timeout=10) as r:
                if r.status == 200:
                    report["deploy"] = "verificado"
                    break
        except OSError:
            pass
        time.sleep(10)
    else:
        report["deploy"] = "no verificado en 5 min (revisar Vercel)"
    r = subprocess.run([sys.executable, "pipeline/indexnow_submit.py"],
                       capture_output=True, text=True, cwd=ROOT)
    report["indexnow"] = (r.stdout or r.stderr).strip()


def render_report(report: dict) -> str:
    L = [f"# Edición {report['fecha']}" + (" (dry-run)" if report.get("dry_run") else ""),
         "", f"**Resultado:** {report.get('resultado', '?')}"]
    if report.get("error"):
        L += ["", f"**Error:** `{report['error']}`"]
    if report.get("publicados"):
        L += ["", "## Publicados", ""]
        L += [f"- [{p['titulo']}](https://www.radarinmobiliario.com/noticia/{p['slug']}) "
              f"— verificado por {p['verificador']}" for p in report["publicados"]]
    if report.get("rechazados"):
        L += ["", "## Rechazados (puerta 2)", ""]
        L += [f"- {r['titulo']} — {r['motivo']} ({r['verificador']})"
              for r in report["rechazados"]]
    if report.get("descartados_p1"):
        L += ["", "## Descartados (puerta 1)", ""]
        L += [f"- {t} — {m}" for t, m in report["descartados_p1"]]
    if report.get("archivadas"):
        L += ["", f"_{len(report['archivadas'])} notas caducadas archivadas._"]
    meta = [str(report.get(k, "")) for k in ("commit", "deploy", "indexnow")]
    L += ["", "---", f"Commit: {meta[0]} · Deploy: {meta[1]} · IndexNow: {meta[2]} · "
          f"Duración: {report.get('duracion_min', '?')} min"]
    return "\n".join(L) + "\n"


def write_report(report: dict, dry_run: bool) -> None:
    EDICIONES.mkdir(parents=True, exist_ok=True)
    suffix = "-dryrun" if dry_run else ""
    path = EDICIONES / f"{report['fecha']}{suffix}.md"
    path.write_text(render_report(report), encoding="utf-8")
    print(f"Informe: {path}")


def notify(title: str, message: str) -> None:
    try:
        subprocess.run(["osascript", "-e",
                        f"display notification {json.dumps(message)} "
                        f"with title {json.dumps(title)}"],
                       capture_output=True, timeout=10)
    except (OSError, subprocess.TimeoutExpired):
        pass  # sin GUI (ssh) o colgado — el informe ya quedó escrito


class _NoEdition(Exception):
    """Día sin edición (legítimo, no error)."""


def main() -> int:
    dry_run = "--dry-run" in sys.argv
    t0 = datetime.now()
    today = date.today()
    report = {"fecha": today.isoformat(), "dry_run": dry_run, "publicados": [],
              "rechazados": [], "descartados_p1": []}

    if LOCK.exists() and LOCK.read_text().strip() == today.isoformat() and not dry_run:
        print("Ya hay edición hoy — no-op.")
        return 0

    try:
        preflight(report)

        # 1. fetch + PUERTA 1
        sh([sys.executable, "pipeline/fetch_news.py"])
        candidates = json.loads((WORK / "candidates.json").read_text(encoding="utf-8"))
        # C1 — prev es siempre lo último PUBLICADO (HEAD), nunca un working
        # tree a medias.
        prev = parse_news_data(sh(["git", "show", "HEAD:src/data/news.js"]).stdout)
        seen = collect_seen_urls(prev["items"], [PUBLICADO, RECHAZADAS, ARCHIVO])
        ok, ko = filter_candidates(candidates, seen, today)
        report["descartados_p1"] = [(c["titulo"][:60], motivo) for c, motivo in ko]
        if not ok:
            report["resultado"] = "sin candidatos que pasen la puerta 1 — no hay edición"
            raise _NoEdition()
        (WORK / "candidates.json").write_text(
            json.dumps(ok, indent=2, ensure_ascii=False), encoding="utf-8")

        # 2. triage (Ollama --auto; fallback triage_claude)
        triage_script = "pipeline/triage_ollama.py" if report["ollama"] else "pipeline/triage_claude.py"
        args = [sys.executable, triage_script]
        if triage_script.endswith("ollama.py"):
            args.append("--auto")
        sh(args)
        if not triage_script.endswith("ollama.py"):
            # triage_claude no conoce --auto: marcar las notas de hoy a mano
            hoy = date.today().strftime("%Y%m%d")
            for f in COLA.glob(f"{hoy}-*.md"):
                t = f.read_text(encoding="utf-8")
                f.write_text(t.replace("publicar: false", "publicar: true\nmodo: auto", 1),
                             encoding="utf-8")

        # I3 — el triaje puede descartar todos los candidatos (ninguna nota
        # queda en publicar: true); en ese caso no hay edición que pulir.
        n_aprobadas = sum(1 for f in COLA.glob("*.md")
                          if "publicar: true" in f.read_text(encoding="utf-8"))
        if n_aprobadas == 0:
            report["resultado"] = "triage descartó todos los candidatos — no hay edición"
            raise _NoEdition()

        # 3. polish (Claude) — mueve las notas a Publicado/ al acabar
        sh(["bash", "pipeline/polish_claude.sh"], timeout=1800)
        approved = json.loads((WORK / "approved.json").read_text(encoding="utf-8"))
        edicion = parse_news_data(NEWS_JS.read_text(encoding="utf-8"))
        today_items = edicion["items"]
        if len(today_items) != len(approved):
            raise SystemExit(f"ABORT: polish produjo {len(today_items)} items "
                             f"pero había {len(approved)} aprobados")

        # 3b. re-pulido vía Codex de los que quedaron degradados
        today_h = datetime.now().strftime("%-d %b %Y")
        for i, item in enumerate(today_items):
            if needs_repolish(item):
                today_items[i] = repolish_item(item, approved[i], today_h)

        # 4. PUERTA 2 — verificación por artículo
        survivors = []
        for item, source in zip(today_items, approved):
            verdict, motivo, who = vc.verify_with_fallback(item, source)
            if verdict == "APPROVE":
                survivors.append(item)
                report["publicados"].append(
                    {"titulo": item["titulo"], "slug": item["slug"], "verificador": who})
            elif who == "ninguno":
                # I1 — verificador caído no es lo mismo que rechazo editorial:
                # abortar sin reject_note ni lock, para que el reintento de las
                # 14:00 vuelva a probar con el material intacto.
                raise SystemExit("ABORT puerta 2: sin verificador disponible "
                                 "(codex y claude caídos)")
            else:
                report["rechazados"].append(
                    {"titulo": item.get("titulo", "?"), "motivo": motivo, "verificador": who})
                if not dry_run:
                    reject_note(source.get("url", ""), motivo)
        if not survivors:
            # restaurar el news.js anterior: la edición de hoy no existe
            NEWS_JS.write_text(render_news_js(prev["actualizado"], prev["semanaResumen"],
                                              prev["destacada"], prev["items"]),
                               encoding="utf-8")
            report["resultado"] = "todos los artículos rechazados en puerta 2 — no hay edición"
            raise _NoEdition()

        # 5. merge con archivo + destacada (I2 — siempre verificada + métricas
        # reales, nunca la reescritura sin verificar del dest_prompt de polish)
        destacada = {**survivors[0], "metricas": _metricas_reales(survivors)}
        distritos = len({s.get("distrito") for s in survivors if s.get("distrito")})
        semana = {"publicadas": len(survivors), "distritosCubiertos": distritos or 1,
                  "movimientoMedio": _movimiento_medio(prev)}
        merged = merge_items(survivors, prev["items"])
        NEWS_JS.write_text(render_news_js(edicion["actualizado"], semana, destacada, merged),
                           encoding="utf-8")

        # 6. PUERTA 3 + publicación
        gate3(report)
        if dry_run:
            report["resultado"] = ("dry-run OK — working tree con cambios para inspección; "
                                   "restaurar con: git checkout -- . ")
        else:
            publish(survivors, report)
            LOCK.write_text(today.isoformat(), encoding="utf-8")
            report["resultado"] = f"publicados {len(survivors)} artículos"

    except _NoEdition:
        if not dry_run:
            LOCK.write_text(today.isoformat(), encoding="utf-8")
    except (SystemExit, subprocess.CalledProcessError, Exception) as e:
        # I7 — cuando el fallo es un subprocess con stderr, incluirlo: es la
        # única pista real de qué rompió (git, build.py, distribute.py…).
        if isinstance(e, subprocess.CalledProcessError):
            report["error"] = f"{e} :: stderr: {(e.stderr or '')[-500:]}"
        else:
            report["error"] = str(e)[:500]
        report["resultado"] = "ERROR — sin publicar"
        write_report(report, dry_run)
        notify("Radar: edición FALLIDA", str(e)[:150])
        return 1

    report["duracion_min"] = round((datetime.now() - t0).total_seconds() / 60, 1)
    write_report(report, dry_run)
    notify("Radar: edición del día",
           report.get("resultado", "") + f" · {len(report['rechazados'])} rechazados")
    return 0


if __name__ == "__main__":
    sys.exit(main())
