#!/usr/bin/env python3
"""auto_edition.py — Orquestador de la edición diaria autónoma.

Flujo: preflight → fetch → PUERTA 1 → triage (Ollama, --auto) → polish (Claude)
→ PUERTA 2 (verify_codex) → merge con archivo → PUERTA 3 → publish → informe.
Diseño: docs/superpowers/specs/2026-07-02-auto-edition-design.md

Uso: python3 pipeline/auto_edition.py [--dry-run]
"""
import json
import re
import subprocess
import sys
from datetime import date, datetime, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from distribute import _split_top_level_objects  # parser balanceado ya probado

ROOT = Path(__file__).parent.parent
NEWS_JS = ROOT / "src" / "data" / "news.js"
WORK = ROOT / "pipeline" / "work"
VAULT = Path.home() / "Documents" / "Radar Inmobiliario" / "Contenido"
COLA = VAULT / "Noticias" / "_cola"
PUBLICADO = VAULT / "Noticias" / "Publicado"
RECHAZADAS = VAULT / "Noticias" / "_rechazadas"
ARCHIVO = VAULT / "Noticias" / "_archivo"
EDICIONES = VAULT / "Ediciones"

MIN_SCORE = 5
MAX_ARTICULOS = 4
CAP_ITEMS = 30
FUENTES_BLACKLIST = set()  # nombres de fuente en minúsculas, p.ej. {"forocoches"}


# ── news.js: parse / merge / render ──────────────────────────────────────────

def _balanced_span(text: str, anchor_regex: str, open_ch: str, close_ch: str):
    """Texto del bloque balanceado (incluidos delimitadores) tras el anchor."""
    m = re.search(anchor_regex, text, re.M)
    if not m:
        return None
    i = text.find(open_ch, m.end() - 1)
    if i < 0:
        return None
    depth, in_str, esc = 0, False, False
    for j in range(i, len(text)):
        c = text[j]
        if in_str:
            if esc:
                esc = False
            elif c == "\\":
                esc = True
            elif c == '"':
                in_str = False
            continue
        if c == '"':
            in_str = True
        elif c == open_ch:
            depth += 1
        elif c == close_ch:
            depth -= 1
            if depth == 0:
                return text[i:j + 1]
    return None


def parse_news_data(text: str) -> dict:
    m = re.search(r"^  actualizado:\s*'((?:[^'\\]|\\.)*)'", text, re.M)
    actualizado = re.sub(r"\\(.)", r"\1", m.group(1)) if m else ""
    semana_txt = _balanced_span(text, r"^  semanaResumen:\s*\{", "{", "}") or "{}"
    dest_txt = _balanced_span(text, r"^  destacada:\s*\{", "{", "}") or "{}"
    items_txt = _balanced_span(text, r"^  items:\s*\[", "[", "]") or "[]"
    items = [json.loads(o) for o in _split_top_level_objects(items_txt[1:-1])]
    return {
        "actualizado": actualizado,
        "semanaResumen": json.loads(semana_txt),
        "destacada": json.loads(dest_txt),
        "items": items,
    }


def merge_items(new_items: list, prev_items: list, cap: int = CAP_ITEMS) -> list:
    def key(it):
        return it.get("url") or it.get("slug") or ""
    seen = {key(it) for it in new_items}
    merged = list(new_items)
    for it in prev_items:
        k = key(it)
        if k and k in seen:
            continue
        seen.add(k)
        merged.append(it)
    return merged[:cap]


def render_news_js(actualizado: str, semana: dict, destacada: dict, items: list) -> str:
    actualizado_js = actualizado.replace("\\", "\\\\").replace("'", "\\'")
    return f"""// Enriched news data for the redesigned "noticias" section.
// Each item carries: fecha, hora, categoria, distrito, fuente, titulo, resumen,
// impactoPrecio (estimated bps for the affected zone), tag (color hint).
// Generated by pipeline/polish_claude.sh + pipeline/auto_edition.py

window.NEWS_DATA = {{
  actualizado: '{actualizado_js}',
  semanaResumen: {json.dumps(semana, indent=2, ensure_ascii=False)},

  // Featured "hero" piece — the lead story
  destacada: {json.dumps(destacada, indent=2, ensure_ascii=False)},

  items: {json.dumps(items, indent=2, ensure_ascii=False)},
}};
"""
